#!/usr/bin/env bash
# Install nginx web server
sudo su
apt update
apt install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "/listen 80 default_server;/a \\\trewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\terror_page 404 /404.html;" /etc/nginx/sites-available/default
service nginx restart
